app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HOME, name="home"),
    path('base/', views.BASE, name="base"),
    path('products/', views.PRODUCT, name="products"),
    path('products/<str:id>', views.PRODUCT_DETAIL_PAGE, name="product_detail"),
    path('search/', views.SEARCH, name="search"),
    path('contact/', views.CONTACT_PAGE, name="contact"),

    path('register/', views.HandleRegister, name="register"),
    path('login/', views.HandleLogin, name="login"),
    path('logout/', views.HandleLogout, name="logout"),
   

    #cart
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

    path('cart/checkout/', views.Check_out, name="checkout"),

    path('cart/checkout/placeorder', views.PLACE_ORDER, name="place_order"),
    
    path('success', views.success, name="success"),
    path('about', views.about, name="about"),
    path('blog', views.blog, name="blog"),
    path('blog_singer', views.blog_singer, name="blog_singer"),
    path('blog_singer2', views.blog_singer2, name="blog_singer2"),



    



] 

mohinh/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

app/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Categories(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class Color(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Filter_Price(models.Model):
    FILTER_PRICE =(
        ('99.000 TO 129.000','99.000 TO 129.000'),
        ('130.000 TO 200.000','130.000 TO 200.000'),
    )

    price = models.CharField(choices=FILTER_PRICE,max_length=60)

    def __str__(self):
        return self.price

class Product(models.Model):
    CONDITION = (('New','New'),('Old','Old') )
    STOCK = (('IN STOCK','IN STOCK'),('OUT OF STOCK','OUT OF STOCK') )
    STATUS = (('Publish','Publish'),('Draft','Draft') )

    unique_id = models.CharField(unique=True,max_length=200,null=True,blank=True)
    image = models.ImageField(upload_to='Product_images/img')
    name = models.CharField(max_length=200)
    price= models.IntegerField()
    condition = models.CharField(choices=CONDITION,max_length=100)
    information = models.TextField()
    description = models.TextField()
    stock = models.CharField(choices=STOCK,max_length=200)
    status = models.CharField(choices=STATUS,max_length=200)
    create_date = models.DateTimeField(default=timezone.now)

    categories = models.ForeignKey(Categories,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    filter_price = models.ForeignKey(Filter_Price,on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        if self.unique_id is None and self.create_date and self.id:
            self.unique_id = self.create_date.strftime('75%Y%m%d23') + str(self.id)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

class Images(models.Model):
    image = models.ImageField(upload_to='Product_images/img')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)

    

class Tag(models.Model):
    name = models.CharField(max_length=200)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)


class Contact_us(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=300)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
    

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    address = models.TextField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postcode = models.IntegerField()
    phone = models.IntegerField()
    email = models.CharField(max_length=100)
    
    amount = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=300,null=True,blank=True)
    paid = models.BooleanField(default=False,null=True)
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return self.user.username
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)       
    image = models.ImageField(upload_to="Product_Images/Order_Img")
    quantity = models.CharField(max_length=20)
    price = models.CharField(max_length=50)
    total = models.CharField(max_length=1000)   
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.order.user.username
    
   
    
    

app/templates/Main/about.html
{%  extends 'Main/base.html' %}

{% block content %} 
{% load static  %}
 <!-- About section Start -->
   <!-- breadcrumb-area start -->
   <div class="breadcrumb-area">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12 text-center">
                <h2 class="breadcrumb-title">Giới thiệu</h2>
                <!-- breadcrumb-list start -->
                <ul class="breadcrumb-list">
                    <li class="breadcrumb-item"><a href="{% url 'home'%}">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Giới thiệu</li>
                </ul>
                <!-- breadcrumb-list end -->
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-area end -->
<!-- About section Start -->
<div class="about-area pt-100px">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="about-wrapper text-center">
                    <div class="about-contant">
                        <h2 class="title">
                            <span>GIỚI THIỆU MOHINHKIMETSU </span>
                            
                        </h2>
                        <p> Chào mừng bạn đến với cửa hàng chuyên cung cấp mô hình Kimetsu no Yaiba – một thiên đường dành cho những người hâm mộ đam mê bộ truyện tranh và anime nổi tiếng này! Tại đây, chúng tôi tự hào giới thiệu một bộ sưu tập đa dạng và phong phú của các mô hình, đảm bảo mang lại trải nghiệm tuyệt vời cho các fan của Kimetsu no Yaiba.

                            Cửa hàng của chúng tôi mang đến sự đa dạng với các sản phẩm từ các nhân vật nổi tiếng như Tanjiro Kamado, Nezuko Kamado, Zenitsu Agatsuma, Inosuke Hashibira và nhiều nhân vật khác. Chất lượng của mỗi mô hình được đảm bảo cao cấp, với chi tiết tinh tế và chân thực, giúp tái tạo chính xác các đặc điểm nổi bật của nhân vật trong series.</p>
                    </div>
                    <div class="promo-video">
                        <img src="{% static "assets/images/hero/inner-img/anh20.jpg" %}" alt="">
                        <a href="https://www.youtube.com/watch?v=MzShJ1XyAhs" class="venobox overlay-box" data-vbtype="video"><span
                            class="fa fa-play"><i class="ripple"></i></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About section End -->
<!-- About section End -->
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock%}

app/templates/Main/blog.html
{%  extends 'Main/base.html' %}

{% block content %} 
{% load static%}
<!-- breadcrumb-area start -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12 text-center">
                <h2 class="breadcrumb-title">Bài viết</h2>
                <!-- breadcrumb-list start -->
                <ul class="breadcrumb-list">
                    <li class="breadcrumb-item"><a href="{% url 'home'%}">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Bài viết</li>
                </ul>
                <!-- breadcrumb-list end -->
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-area end -->
  <!-- Blog Area Start -->
  <div class="blog-list pb-100px pt-100px main-blog-page single-blog-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ms-auto me-auto">
                <div class="row">
                    <div class="col-12 mb-50px">
                        <div class="single-blog">
                            <div class="blog-image">
                                <a href="{% url 'blog_singer2'%}"><img src="{% static "assets/images/blog-image/anh12.jpg" %}" class="img-responsive w-100" alt=""></a>
                            </div>
                            <div class="blog-text">
                                <div class="blog-athor-date line-height-1">
                                    <span class="blog-date"><i class="fa fa-calendar" aria-hidden="true"></i> 05-05-2024</span>
                                    <span><a class="blog-author" href="blog-grid.html"><i class="fa fa-user" aria-hidden="true"></i> Nguyễn Văn Tiền</a></span>
                                </div>
                                <h5 class="blog-heading"><a class="blog-heading-link" href="{% url 'blog_singer2'%}">Nhân vật Kamado Tanjiro</a></h5>
                                <p>Tanjiro Kamado là nhân vật chính của bộ truyện “Kimetsu no Yaiba”, một chàng trai trẻ có trái tim nhân từ và ý chí mạnh mẽ. Dù phải đối mặt với nhiều gian khổ và thử thách, Tanjiro luôn giữ vững niềm tin và quyết tâm đi tìm con đường của mình. Ban đầu, Tanjiro […]</p>
                                <a href="{% url 'blog_singer2'%}" class="btn btn-primary blog-btn"> Đọc tiếp</a>
                            </div>
                        </div>
                    </div>
                    <!-- End single blog -->
                    <div class="col-12 mb-50px">
                        <div class="single-blog ">
                            <div class="blog-image">
                                <a href="{% url 'blog_singer'%}"><img src="{% static "assets/images/blog-image/anh10.jpg" %}" class="img-responsive w-100" alt=""></a>
                            </div>
                            <div class="blog-text">
                                <div class="blog-athor-date line-height-1">
                                    <span class="blog-date"><i class="fa fa-calendar" aria-hidden="true"></i> 05-05-2024</span>
                                    <span><a class="blog-author" href="blog-grid.html"><i class="fa fa-user" aria-hidden="true"></i> Nguyễn Đức Thắng</a></span>
                                </div>
                                <h5 class="blog-heading"><a class="blog-heading-link" href="{% url 'blog_singer'%}">Nhân vật Hashibira Inosuke</a></h5>
                                <p>Hashibira Inosuke là một nhân vật trong bộ truyện “Kimetsu no Yaiba” và là một trong những thành viên của nhóm săn quỷ cùng với Tanjiro, Nezuko và Zenitsu. Inosuke là một chàng trai mạnh mẽ và dũng mãnh, luôn sống mạnh mẽ và quyết đoán. Anh ta có bản tính hoang […]</p>
                                <a href="{% url 'blog_singer'%}" class="btn btn-primary blog-btn"> Đọc tiếp</a>
                            </div>
                        </div>
                    </div>
                    <!-- End single blog -->
                   
                </div>
            </div>
        </div>
        <!--  Pagination Area Start -->
        <div class="pro-pagination-style text-center mt-0 mb-0" data-aos="fade-up" data-aos-delay="200">
            <div class="pages">
                <ul>
                    <li class="li"><a class="page-link" href="#"><i class="fa fa-angle-left"></i></a></li>
                    <li class="li"><a class="page-link active" href="#">1</a></li>
                    <li class="li"><a class="page-link" href="#">2</a></li>
                    <li class="li"><a class="page-link" href="#">3</a></li>
                    <li class="li"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!--  Pagination Area End -->
    </div>
</div>
<!-- Blag Area End -->
{% endblock %}

app/templates/Main/blog_singer.html
{%  extends 'Main/base.html' %}

{% block content %} 
{% load static%}
<!-- breadcrumb-area start -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12 text-center">
                <h2 class="breadcrumb-title">Bài viết</h2>
                
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-area end -->
<!-- Blog Area Start -->
<div class="blog-grid pb-100px pt-100px main-blog-page single-blog-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 offset-lg-2">
                <div class="blog-posts">
                    <div class="single-blog-post blog-grid-post">
                        <div class="blog-image single-blog">
                            <img class="img-fluid h-auto border-radius-10px" src="{% static "assets/images/blog-image/anh10.jpg" %}" alt="blog" />
                        </div>
                        <div class="blog-post-content-inner mt-30px">
                            <div class="blog-athor-date">
                                <span class="blog-date"><i class="fa fa-calendar" aria-hidden="true"></i>05-05-2024</span>
                                <span><a class="blog-author" href="blog-grid.html"><i class="fa fa-user" aria-hidden="true"></i> Nguyễn Đức Thắng</a></span>
                            </div>
                            <h4 class="blog-title">Nhân vật Hashibira Inosuke </h4>
                            <p data-aos="fade-up">
                                Hashibira Inosuke là một nhân vật trong bộ truyện “Kimetsu no Yaiba” và là một trong những thành viên của nhóm săn quỷ cùng với Tanjiro, Nezuko và Zenitsu.

                                Inosuke là một chàng trai mạnh mẽ và dũng mãnh, luôn sống mạnh mẽ và quyết đoán. Anh ta có bản tính hoang dã và thích chiến đấu, thường xuyên mặc một bộ giáp từ những phần của quỷ mà anh ta đã giết để tạo ra vũ khí và bảo vệ bản thân.
                                
                                Mặc dù có vẻ ngoài hùng hổ và thô lỗ, Inosuke cũng có một bên tốt và thể hiện sự quan tâm đến đồng đội của mình, đặc biệt là đối với Tanjiro. Dù thường xuyên tranh cãi và gây rối, Inosuke vẫn là một phần không thể thiếu của nhóm và đã đóng góp vào nhiều trận chiến quan trọng trong cuộc phiêu lưu của họ.
                                
                                Một điểm đặc biệt của Inosuke là khả năng chiến đấu mạnh mẽ và linh hoạt, cũng như sự sáng tạo trong việc sử dụng vũ khí và kỹ năng chiến đấu. Mặc dù có tính cách cứng đầu và không chịu khuất phục, Inosuke cũng đã thể hiện sự tiến bộ trong việc làm việc nhóm và hợp tác với đồng đội của mình.
                                
                                Hashibira Inosuke là một nhân vật độc đáo và có sức hút trong “Kimetsu no Yaiba”, và tính cách mạnh mẽ và linh hoạt của anh ta đã thu hút sự yêu mến từ phía người hâm mộ.
                            </p>
                            
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Blag Area End -->
{% endblock %}

app/templates/Main/product_singer.html
{%  extends 'Main/base.html' %}

{% block content %} 

<!-- Product Details Area Start -->
<div class="product-details-area pt-100px pb-100px">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                <!-- Swiper -->
                <div class="swiper-container zoom-top">
                    <div class="swiper-wrapper">
                        {%for i in prod.images_set.all %}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                            <a class="venobox full-preview" data-gall="myGallery" href="/{{i.image}}">
                                <i class="fa fa-arrows-alt" aria-hidden="true"></i>
                            </a>
                        </div>
                        {% endfor %}
                       
                    </div>
                </div>
                <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
                    <div class="swiper-wrapper">
                        {%for i in prod.images_set.all %}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="/{{i.image}}" alt="">
                        </div>
                        {% endfor %}
                        
                    </div>
                    <!-- Add Arrows -->
                    <div class="swiper-buttons">
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                <div class="product-details-content quickview-content ml-25px">
                    <h2>{{prod.name}}</h2>
                    <div class="pricing-meta">
                        <ul class="d-flex">
                            <li class="new-price">{{prod.price}} VND</li>
                        </ul>
                    </div>
                    <div class="pro-details-rating-wrap">
                        <div class="rating-product">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <span class="read-review"><a class="reviews" href="#"></a></span>
                    </div>
                    <p class="mt-30px"> {{prod.information}}</p>
                    
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>danh mục: </span>
                        <ul class="d-flex">
                            <li>
                                <a href="#">{{prod.categories}} </a>
                            </li>
                            
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>Từ khóa: </span>
                        <ul class="d-flex">
                            <li>
                                {% for i in prod.tag_set.all %}
                                <a href="#">{{i.name}}, </a>
                                {% endfor %}
                            </li>
                            
                        </ul>
                    </div>
                    <div class="pro-details-quality">
                        <div class="cart-plus-minus">
                            <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1" />
                        </div>
                        <div class="pro-details-cart">
                            <a href="{% url 'cart_add' prod.id  %}"><button class="add-cart"> Thêm vào
                                giỏ</button></a>
                        </div>
                        
                    </div>
                </div>
                <!-- product details description area start -->
                <div class="description-review-wrapper">
                    <div class="description-review-topbar nav">
                        <button data-bs-toggle="tab" data-bs-target="#des-details2">Miêu tả</button>
                        <button class="active" data-bs-toggle="tab" data-bs-target="#des-details1">Thông tin</button>
                        <button data-bs-toggle="tab" data-bs-target="#des-details3">Đánh giá (02)</button>
                    </div>
                    <div class="tab-content description-review-bottom">
                        <div id="des-details2" class="tab-pane">
                            <div class="product-anotherinfo-wrapper text-start">
                                <ul>
                                    <li> {{prod.information}}</li>
                                
                                </ul>
                            </div>
                        </div>
                        <div id="des-details1" class="tab-pane active">
                            <div class="product-description-wrapper">
                                <p>
                                    <ul>
                                        <li> {{prod.description}}</li>
                                    
                                    </ul>
                                </p>
                            </div>
                        </div>
                        <div id="des-details3" class="tab-pane">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="review-wrapper">
                                        <div class="single-review">
                                            <div class="review-img">
                                                <img src="assets/images/review-image/1.png" alt="" />
                                            </div>
                                            <div class="review-content">
                                                <div class="review-top-wrap">
                                                    <div class="review-left">
                                                        <div class="review-name">
                                                            <h4>White Lewis</h4>
                                                        </div>
                                                        <div class="rating-product">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-left">
                                                        <a href="#">Reply</a>
                                                    </div>
                                                </div>
                                                <div class="review-bottom">
                                                    <p>
                                                        Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                                                        cubilia Curae Suspendisse viverra ed viverra. Mauris ullarper
                                                        euismod vehicula. Phasellus quam nisi, congue id nulla.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="single-review child-review">
                                            <div class="review-img">
                                                <img src="assets/images/review-image/2.png" alt="" />
                                            </div>
                                            <div class="review-content">
                                                <div class="review-top-wrap">
                                                    <div class="review-left">
                                                        <div class="review-name">
                                                            <h4>White Lewis</h4>
                                                        </div>
                                                        <div class="rating-product">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-left">
                                                        <a href="#">Reply</a>
                                                    </div>
                                                </div>
                                                <div class="review-bottom">
                                                    <p>Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                                                        cubilia Curae Sus pen disse viverra ed viverra. Mauris ullarper
                                                        euismod vehicula.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="ratting-form-wrapper pl-50">
                                        <h3>Add a Review</h3>
                                        <div class="ratting-form">
                                            <form action="#">
                                                <div class="star-box">
                                                    <span>Your rating:</span>
                                                    <div class="rating-product">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="rating-form-style">
                                                            <input placeholder="Name" type="text" />
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="rating-form-style">
                                                            <input placeholder="Email" type="email" />
                                                        </div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="rating-form-style form-submit">
                                                            <textarea name="Your Review" placeholder="Message"></textarea>
                                                            <button class="btn btn-primary btn-hover-color-primary " type="submit" value="Submit">Submit</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- product details description area end -->
            </div>
        </div>
    </div>
</div>
<!-- Product Area Start -->

{% endblock %}